### ISSUE TITLE
TypeError: compile() expected string without null bytes

### ISSUE THREAD

**Issue by adiroiban** [twisted/twistedchecker#118]
See https://travis-ci.org/twisted/twisted/jobs/148667038

this is produced if we run twistedchecker 

we also got this errors in the past, is just that they were hidden among the many linter errors.

```
Traceback (most recent call last):
  File "/home/travis/build/twisted/twisted/build/txchecker-travis/lib/python2.7/site-packages/pylint/lint.py", line 586, in get_astng
    return MANAGER.astng_from_file(filepath, modname, source=True)
  File "/home/travis/build/twisted/twisted/build/txchecker-travis/lib/python2.7/site-packages/logilab/astng/manager.py", line 104, in astng_from_file
    return ASTNGBuilder(self).file_build(filepath, modname)
  File "/home/travis/build/twisted/twisted/build/txchecker-travis/lib/python2.7/site-packages/logilab/astng/builder.py", line 128, in file_build
    node = self.string_build(data, modname, path)
  File "/home/travis/build/twisted/twisted/build/txchecker-travis/lib/python2.7/site-packages/logilab/astng/builder.py", line 134, in string_build
    module = self._data_build(data, modname, path)
  File "/home/travis/build/twisted/twisted/build/txchecker-travis/lib/python2.7/site-packages/logilab/astng/builder.py", line 150, in _data_build
    node = parse(data + '\n')
  File "/home/travis/build/twisted/twisted/build/txchecker-travis/lib/python2.7/site-packages/logilab/astng/builder.py", line 39, in parse
    return compile(string, "<string>", 'exec', PyCF_ONLY_AST)
TypeError: compile() expected string without null bytes
Traceback (most recent call last):
  File "/home/travis/build/twisted/twisted/build/txchecker-travis/lib/python2.7/site-packages/pylint/lint.py", line 586, in get_astng
    return MANAGER.astng_from_file(filepath, modname, source=True)
  File "/home/travis/build/twisted/twisted/build/txchecker-travis/lib/python2.7/site-packages/logilab/astng/manager.py", line 104, in astng_from_file
    return ASTNGBuilder(self).file_build(filepath, modname)
  File "/home/travis/build/twisted/twisted/build/txchecker-travis/lib/python2.7/site-packages/logilab/astng/builder.py", line 128, in file_build
    node = self.string_build(data, modname, path)
  File "/home/travis/build/twisted/twisted/build/txchecker-travis/lib/python2.7/site-packages/logilab/astng/builder.py", line 134, in string_build
    module = self._data_build(data, modname, path)
  File "/home/travis/build/twisted/twisted/build/txchecker-travis/lib/python2.7/site-packages/logilab/astng/builder.py", line 150, in _data_build
    node = parse(data + '\n')
  File "/home/travis/build/twisted/twisted/build/txchecker-travis/lib/python2.7/site-packages/logilab/astng/builder.py", line 39, in parse
    return compile(string, "<string>", 'exec', PyCF_ONLY_AST)
TypeError: compile() expected string without null bytes
Traceback (most recent call last):
  File "/home/travis/build/twisted/twisted/build/txchecker-travis/lib/python2.7/site-packages/pylint/lint.py", line 586, in get_astng
    return MANAGER.astng_from_file(filepath, modname, source=True)
  File "/home/travis/build/twisted/twisted/build/txchecker-travis/lib/python2.7/site-packages/logilab/astng/manager.py", line 104, in astng_from_file
    return ASTNGBuilder(self).file_build(filepath, modname)
  File "/home/travis/build/twisted/twisted/build/txchecker-travis/lib/python2.7/site-packages/logilab/astng/builder.py", line 128, in file_build
    node = self.string_build(data, modname, path)
  File "/home/travis/build/twisted/twisted/build/txchecker-travis/lib/python2.7/site-packages/logilab/astng/builder.py", line 134, in string_build
    module = self._data_build(data, modname, path)
  File "/home/travis/build/twisted/twisted/build/txchecker-travis/lib/python2.7/site-packages/logilab/astng/builder.py", line 150, in _data_build
    node = parse(data + '\n')
  File "/home/travis/build/twisted/twisted/build/txchecker-travis/lib/python2.7/site-packages/logilab/astng/builder.py", line 39, in parse
    return compile(string, "<string>", 'exec', PyCF_ONLY_AST)
TypeError: compile() expected string without null bytes
```

**Comment by tomprince** [comment]
This is caused by 
```
src/twisted/test/raiser.so
src/twisted/runner/portmap.so
src/twisted/python/_sendmsg.so
```
trying to be opened as python files.

This happens in two places, once in `twistedchecker/core/exceptionfinder.py` and once somewhere inside pylint.

**Comment by tomprince** [comment]
```
diff --git a/twistedchecker/core/exceptionfinder.py b/twistedchecker/core/exceptionfinder.py
index 1557cdb..b8cc0d3 100644
--- a/twistedchecker/core/exceptionfinder.py
+++ b/twistedchecker/core/exceptionfinder.py
@@ -73,7 +73,9 @@ def findAllExceptions(pathToCheck):
     """
     finder = PatternFinder()
     if os.path.isfile(pathToCheck):
-        findPatternsInFile(open(pathToCheck).read(), finder)
+        _, extname = os.path.splitext(pathToCheck)
+        if extname == ".py":
+            findPatternsInFile(open(pathToCheck).read(), finder)
     else:
         for path, dirs, files in os.walk(pathToCheck):
             for file in files:
```
fixes the first error, uncovering the second. I'm not sure if the second can be addressed without changing pylint.
