### ISSUE TITLE
modifiedBlankLines() takes 7 positional arguments but 9 were given

### ISSUE THREAD

**Issue by jfhbrook** [twisted/twistedchecker#138]
When running twisted's linting tox task, I got a traceback like this:

```
Traceback (most recent call last):
  File "/home/josh/software/jfhbrook/twisted/build/lint/bin/twistedchecker", line 10, in <module>
    sys.exit(main())
  File "/home/josh/software/jfhbrook/twisted/build/lint/lib/python3.5/site-packages/twistedchecker/core/runner.py", line 439, in main
    runner.run(sys.argv[1:])
  File "/home/josh/software/jfhbrook/twisted/build/lint/lib/python3.5/site-packages/twistedchecker/core/runner.py", line 315, in run
    self.linter.check(args)
  File "/home/josh/software/jfhbrook/twisted/build/lint/lib/python3.5/site-packages/pylint/lint.py", line 736, in check
    self._do_check(files_or_modules)
  File "/home/josh/software/jfhbrook/twisted/build/lint/lib/python3.5/site-packages/pylint/lint.py", line 867, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/home/josh/software/jfhbrook/twisted/build/lint/lib/python3.5/site-packages/pylint/lint.py", line 947, in check_astroid_module
    walker.walk(ast_node)
  File "/home/josh/software/jfhbrook/twisted/build/lint/lib/python3.5/site-packages/pylint/utils.py", line 935, in walk
    cb(astroid)
  File "/home/josh/software/jfhbrook/twisted/build/lint/lib/python3.5/site-packages/twistedchecker/checkers/pycodestyleformat.py", line 182, in visit_module
    recorder = PyCodeStyleWarningRecorder(node.file)
  File "/home/josh/software/jfhbrook/twisted/build/lint/lib/python3.5/site-packages/twistedchecker/checkers/pycodestyleformat.py", line 50, in __init__
    self.run()
  File "/home/josh/software/jfhbrook/twisted/build/lint/lib/python3.5/site-packages/twistedchecker/checkers/pycodestyleformat.py", line 79, in run
    pycodestyle.Checker.check_all(self)
  File "/home/josh/software/jfhbrook/twisted/build/lint/lib/python3.5/site-packages/pycodestyle.py", line 2114, in check_all
    self.check_logical()
  File "/home/josh/software/jfhbrook/twisted/build/lint/lib/python3.5/site-packages/pycodestyle.py", line 1999, in check_logical
    for offset, text in self.run_check(check, argument_names) or ():
  File "/home/josh/software/jfhbrook/twisted/build/lint/lib/python3.5/site-packages/pycodestyle.py", line 1928, in run_check
    return check(*arguments)
TypeError: modifiedBlankLines() takes 7 positional arguments but 9 were given
```

I think what happened was that pycodestyle updated its list of arguments for its blank lines check, such that [it doesn't match with `modifiedBlankLinesCheck` anymore.](https://github.com/twisted/twistedchecker/blob/master/twistedchecker/checkers/pycodestyleformat.py#L218)

I *think* this can be fixed by naively introducing the new arguments, but I haven't investigated the changes deeply enough to understand what the new parameters are for or whether the core API has changed enough to require a refactor of `modifiedBlankLines` beyond just changing the call signature.

It seems like linting might be broken because the current version of pycodestyle [updated its list of arguments](https://github.com/PyCQA/pycodestyle/blob/3b258c375c6392b1475a487c0961cf7dbe03f838/pycodestyle.py#L316-L319) so that they don't match the modified one in twistedchecker. A naive patch in the tox environment made this pass but I haven't investigated deeply enough to know for sure. I'll see if there's a ticket tracking this.

**Comment by adiroiban** [comment]
I don't know why this is still used in Twisted.
I was expected to have pycodestyle executed outside of tiwstedcheker https://github.com/twisted/twisted/pull/969

And there is also this upstream merge https://github.com/PyCQA/pycodestyle/pull/733


My suggestion is to remove pycodestyle from twistedchecker and run pycodestyle as a separate job.
AFAIK, pycodestyle upstream now supports Twisted style

**Comment by jfhbrook** [comment]
I see. I flipped through [the blame for tox.ini](https://github.com/twisted/twisted/blame/trunk/tox.ini#L126) and following the thread it looks like https://github.com/twisted/twisted/pull/1043 may have inadvertently pulled an optional twistedchecker task in while trying to consolidate linting?

**Comment by adiroiban** [comment]
Thanks for the search.
I don't have time for twistedchecker... and I think that twisted build should be changed to stop using it :)

Twistedchecker didn't received much love in the last years

**Comment by glyph** [comment]
Is this still broken?
