### ISSUE TITLE
twistedchecker fails when it encounters emacs backup files

### ISSUE THREAD

**Issue by ghost** [twisted/twistedchecker#57]
I ran it on my twisted branch and got this

```
(twistedchecker)[richard@zorin add-setup-1084552]$ twistedchecker twisted
Traceback (most recent call last):
  File "/home/richard/.virtualenvs/twistedchecker/bin/twistedchecker", line 10, in <module>
    Runner().run(sys.argv[1:])
  File "/home/richard/projects/TwistedChecker/branches/add-setup-1084552/twistedchecker/core/runner.py", line 320, in run
    self.setNameExceptions(args)
  File "/home/richard/projects/TwistedChecker/branches/add-setup-1084552/twistedchecker/core/runner.py", line 288, in setNameExceptions
    patternsFunc, patternsClass = findAllExceptions(path)
  File "/home/richard/projects/TwistedChecker/branches/add-setup-1084552/twistedchecker/core/exceptionfinder.py", line 83, in findAllExceptions
    findPatternsInFile(open(pathFile).read(), finder)
IOError: [Errno 2] No such file or directory: '/home/richard/projects/Twisted/branches/static-path-3765/twisted/web/.#static.py'
```

It should only examine actual python modules.

---

Imported from Launchpad using lp2gh.
- date created: 2013-09-01T20:45:16Z
- owner: richardw
- the launchpad url was https://bugs.launchpad.net/bugs/1219555

**Comment by adiroiban** [comment]
@wallrj  I took a look at this but pylint is ugly here.

The problem is that pylint only ignores explicit file or folder paths... without a filemask and does not provide a hook into file filtering code

filtering is done in pylint.utils.expand_modules based on the config.black_list  which populated by the `--ignore` argument.

Can you just change emacs setting to backup files in `.static.py~' format? or maybe you can configure it to make backup outside of source folder?
